# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'abstract.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_textWindow(object):
    def setupUi(self, textWindow):
        textWindow.setObjectName("textWindow")
        textWindow.resize(745, 557)
        self.verticalLayout = QtWidgets.QVBoxLayout(textWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 96, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.text_abstract = QtWidgets.QPlainTextEdit(textWindow)
        self.text_abstract.setObjectName("text_abstract")
        self.horizontalLayout_2.addWidget(self.text_abstract)
        self.text_keywords = QtWidgets.QPlainTextEdit(textWindow)
        self.text_keywords.setObjectName("text_keywords")
        self.horizontalLayout_2.addWidget(self.text_keywords)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 95, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(448, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btn_saveas = QtWidgets.QPushButton(textWindow)
        self.btn_saveas.setObjectName("btn_saveas")
        self.horizontalLayout.addWidget(self.btn_saveas)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 96, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)

        self.retranslateUi(textWindow)
        QtCore.QMetaObject.connectSlotsByName(textWindow)

    def retranslateUi(self, textWindow):
        _translate = QtCore.QCoreApplication.translate
        textWindow.setWindowTitle(_translate("textWindow", "Paper Manager: abstract"))
        self.btn_saveas.setText(_translate("textWindow", "Save PDF as"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    textWindow = QtWidgets.QWidget()
    ui = Ui_textWindow()
    ui.setupUi(textWindow)
    textWindow.show()
    sys.exit(app.exec_())
