# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fucWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fucWindow(object):
    def setupUi(self, fucWindow):
        fucWindow.setObjectName("fucWindow")
        fucWindow.resize(482, 471)
        fucWindow.setStyleSheet("QWidget{\n"
"background-color:\"#ead9ff\"\n"
"\n"
"}\n"
"QPushButton{\n"
"background-color:\"#ff52ae\"\n"
"\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(fucWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 94, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.logo2 = QtWidgets.QLabel(fucWindow)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.logo2.setFont(font)
        self.logo2.setObjectName("logo2")
        self.horizontalLayout_2.addWidget(self.logo2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 94, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.generate = QtWidgets.QPushButton(fucWindow)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.generate.setFont(font)
        self.generate.setObjectName("generate")
        self.gridLayout.addWidget(self.generate, 1, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 4, 1, 1)
        self.images = QtWidgets.QPushButton(fucWindow)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.images.setFont(font)
        self.images.setObjectName("images")
        self.gridLayout.addWidget(self.images, 0, 3, 1, 1)
        self.bookmarks = QtWidgets.QPushButton(fucWindow)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.bookmarks.setFont(font)
        self.bookmarks.setObjectName("bookmarks")
        self.gridLayout.addWidget(self.bookmarks, 1, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 1, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 0, 4, 1, 1)
        self.keywords = QtWidgets.QPushButton(fucWindow)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.keywords.setFont(font)
        self.keywords.setObjectName("keywords")
        self.gridLayout.addWidget(self.keywords, 0, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem10 = QtWidgets.QSpacerItem(461, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem10)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.back = QtWidgets.QPushButton(fucWindow)
        self.back.setObjectName("back")
        self.horizontalLayout.addWidget(self.back)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(fucWindow)
        QtCore.QMetaObject.connectSlotsByName(fucWindow)

    def retranslateUi(self, fucWindow):
        _translate = QtCore.QCoreApplication.translate
        fucWindow.setWindowTitle(_translate("fucWindow", "Paper Manager"))
        self.logo2.setText(_translate("fucWindow", "logo2"))
        self.generate.setText(_translate("fucWindow", "Generate"))
        self.images.setText(_translate("fucWindow", "  Images  "))
        self.bookmarks.setText(_translate("fucWindow", "Bookmark"))
        self.keywords.setText(_translate("fucWindow", "Keywords"))
        self.back.setText(_translate("fucWindow", "back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fucWindow = QtWidgets.QWidget()
    ui = Ui_fucWindow()
    ui.setupUi(fucWindow)
    fucWindow.show()
    sys.exit(app.exec_())
